version: '3'

services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  pokemon-be:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8081:8081"
    depends_on:
      - postgres_db

volumes:
  postgres-db:
    driver: local